### ISSUE TITLE
how to enable/disable for a particular modes?

### ISSUE THREAD

**Issue by jgarvin** [hrehfeld/emacs-smart-hungry-delete#4]
I expected to be able to toggle it on and off, but there doesn't appear to be a mode associated with smart hungry delete.

**Comment by kevinjfoley** [comment]
`smart-hungry-delete` works by rebinding backspace and `C-d` to different functions.  So to enable for only specific modes you can only bind those key's for that mode's map. Here's an example to bind them only for `python-mode`:

```elisp
(use-package smart-hungry-delete
  :bind (:map python-mode-map
         ("<backspace>" . smart-hungry-delete-backward-char)
         ("C-d" . smart-hungry-delete-forward-char))
  :hook
  (python-mode . smart-hungry-delete-default-c-mode-common-hook)
  :defer nil)
```

**Comment by ThibautVerron** [comment]
You can also use remap if you only want to make sure that you don't overwrite backspace when it is mapped to something else (e.g. in ivy).

```
(use-package smart-hungry-delete
  :bind (([remap backward-delete-char-untabify] . smart-hungry-delete-backward-char)
	 ([remap delete-backward-char] . smart-hungry-delete-backward-char)
	 ([remap delete-char] . smart-hungry-delete-forward-char))
  :init (smart-hungry-delete-add-default-hooks))
```

**Comment by hrehfeld** [comment]
> (use-package smart-hungry-delete
>   :bind (([remap backward-delete-char-untabify] . smart-hungry-delete-backward-char)
> 	 ([remap delete-backward-char] . smart-hungry-delete-backward-char)
> 	 ([remap delete-char] . smart-hungry-delete-forward-char))
>   :init (smart-hungry-delete-add-default-hooks))

Thanks so much for the comments, I updated the documentation.
