### ISSUE TITLE
Is there any reason to use killing?

### ISSUE THREAD

**Issue by black7375** [hrehfeld/emacs-smart-hungry-delete#6]
I love the smart-hungry-delete's action.
It is not excessive and is natural.

However, one problem occurred after use.
The deleted spaces appear when pasting.

I looked into the code for a while and was able to find the cause.
https://github.com/hrehfeld/emacs-smart-hungry-delete/blob/7c1d56a92481594e14d40b5fdf6c48657a0108a0/smart-hungry-delete.el#L190

If I change it to `delete-region`, the above does not happen.

**Comment by hrehfeld** [comment]
Fixed by @black7375 in #7  :-)
